In [1]:
import pandas as pd
import numpy as np

In [2]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s[1])

3.0


In [3]:
import pandas as pd
import numpy as np

dates = pd.date_range('20130101', periods=6)
print(dates)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [4]:
import pandas as pd
import numpy as np

dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)

                   A         B         C         D
2013-01-01  0.929355  0.049159  0.347982 -0.744986
2013-01-02  0.922799 -1.224961  0.500243 -0.098357
2013-01-03 -1.005060 -0.489485 -1.144110  1.085494
2013-01-04 -0.889447  0.033402 -2.459902  1.176031
2013-01-05  0.845318 -0.147381 -0.797909  0.638028
2013-01-06 -0.599797  0.624433  0.236310  0.313091


In [5]:
import pandas as pd
import numpy as np

df2 = pd.DataFrame({'A': 1.,
    'B': pd.Timestamp('20130102'),
    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
    'D': np.array([3] * 4, dtype='int32'),
    'E': pd.Categorical(["test", "train", "test", "train"]),
    'F': 'foo'})
    
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo


In [6]:
df2.iloc[:,2]

0    1.0
1    1.0
2    1.0
3    1.0
Name: C, dtype: float32

In [7]:
print(df2.dtypes)

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


In [8]:
df.tail(2)

A         B         C         D
2013-01-05  0.845318 -0.147381 -0.797909  0.638028
2013-01-06 -0.599797  0.624433  0.236310  0.313091

In [9]:
import pandas as pd
import numpy as np

dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df.columns)

Index(['A', 'B', 'C', 'D'], dtype='object')


In [10]:
import pandas as pd
import numpy as np

dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print(df.to_numpy())

                   A         B         C         D
2013-01-01 -1.769849 -0.395741 -1.181242 -1.409409
2013-01-02  0.755608 -1.432950 -0.039388 -1.252611
2013-01-03  0.365710  1.050940 -1.045043  0.468469
2013-01-04  0.612317  1.505311  1.077740  0.545304
2013-01-05 -0.425790  0.037018 -0.238940  0.770961
2013-01-06 -0.861368 -1.186336 -0.911050  1.521263
[[-1.76984936 -0.39574066 -1.18124173 -1.40940876]
 [ 0.75560812 -1.43295009 -0.03938806 -1.25261054]
 [ 0.36571028  1.05094019 -1.04504267  0.46846912]
 [ 0.61231715  1.50531098  1.07773958  0.54530444]
 [-0.42579032  0.03701762 -0.23894019  0.77096149]
 [-0.86136768 -1.18633588 -0.91104984  1.52126282]]


In [11]:
array_2d = np.array([[1, 2, 3], ['a', 'a', 'c'], [7, 8, 9]])
print(array_2d)

[['1' '2' '3']
 ['a' 'a' 'c']
 ['7' '8' '9']]


In [12]:
import pandas as pd
import numpy as np

dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))

print(df.iloc[:,1].mean())
print(df['A'].std())

0.004139938696695103
0.7053453854230027


In [13]:
import pandas as pd
import numpy as np

dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print(df.T)

                   A         B         C         D
2013-01-01  1.243155 -0.657169 -0.753980  0.894890
2013-01-02 -0.448058 -0.574338 -1.359591 -1.094038
2013-01-03 -0.198169  0.357861 -0.444996  0.254536
2013-01-04 -0.551809 -0.419976 -1.247417  1.083573
2013-01-05  0.773146  1.317868 -0.696014 -0.595305
2013-01-06 -1.648914  0.441211  0.527840  0.263189
   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    1.243155   -0.448058   -0.198169   -0.551809    0.773146   -1.648914
B   -0.657169   -0.574338    0.357861   -0.419976    1.317868    0.441211
C   -0.753980   -1.359591   -0.444996   -1.247417   -0.696014    0.527840
D    0.894890   -1.094038    0.254536    1.083573   -0.595305    0.263189


In [14]:
import pandas as pd
import numpy as np

dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print(df.sort_index(axis=0,ascending=False))
print(df.sort_index(axis=1,ascending=False))

                   A         B         C         D
2013-01-01 -0.908965 -0.664296  1.088457 -0.686994
2013-01-02  0.882534 -0.573298  0.734909 -0.994586
2013-01-03 -1.010520 -0.296851  1.022382  0.654163
2013-01-04 -0.438101  0.739995 -0.238302  1.097466
2013-01-05 -1.152258  0.309696  0.502093 -2.172192
2013-01-06  0.123055  0.073955 -0.699032 -1.230721
                   A         B         C         D
2013-01-06  0.123055  0.073955 -0.699032 -1.230721
2013-01-05 -1.152258  0.309696  0.502093 -2.172192
2013-01-04 -0.438101  0.739995 -0.238302  1.097466
2013-01-03 -1.010520 -0.296851  1.022382  0.654163
2013-01-02  0.882534 -0.573298  0.734909 -0.994586
2013-01-01 -0.908965 -0.664296  1.088457 -0.686994
                   D         C         B         A
2013-01-01 -0.686994  1.088457 -0.664296 -0.908965
2013-01-02 -0.994586  0.734909 -0.573298  0.882534
2013-01-03  0.654163  1.022382 -0.296851 -1.010520
2013-01-04  1.097466 -0.238302  0.739995 -0.438101
2013-01-05 -2.172192  0.502093 

In [15]:
import pandas as pd
import numpy as np

dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df.sort_values(by='B'))

                   A         B         C         D
2013-01-06  0.966950 -0.319092  1.272526  0.345282
2013-01-03  0.096077 -0.030214 -0.730298 -2.543586
2013-01-04 -0.320886  0.286502  0.016111  1.358327
2013-01-05  1.189440  0.617958 -0.917430 -0.440540
2013-01-01  0.223223  1.088783  0.255373  0.015474
2013-01-02 -1.154857  1.209376  0.075362  0.074440


In [34]:
import pandas as pd
import numpy as np

dates = pd.date_range('20130101', periods=6)
print(list('ABCD'))
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print(df[['A','B']])

['A', 'B', 'C', 'D']
                   A         B         C         D
2013-01-01 -1.415481 -0.237072  0.741797 -1.834228
2013-01-02  0.471364 -0.468912  1.472983 -0.047050
2013-01-03  0.552305 -0.301603 -1.356597 -1.602822
2013-01-04  1.079482 -0.375682  0.308604  0.635737
2013-01-05  0.788543  1.087835 -0.151093  0.990019
2013-01-06  0.116421  0.343703  1.523547  0.100652
                   A         B
2013-01-01 -1.415481 -0.237072
2013-01-02  0.471364 -0.468912
2013-01-03  0.552305 -0.301603
2013-01-04  1.079482 -0.375682
2013-01-05  0.788543  1.087835
2013-01-06  0.116421  0.343703


In [23]:
import pandas as pd

# 创建一个 Series，指定自定义索引
data = [1, 3, 5, 7, 9]
custom_index = ['a', 'b', 'c', 'd', 'e']
s = pd.Series(data, index=custom_index)

# 打印 Series
print(s)


a    1
b    3
c    5
d    7
e    9
dtype: int64


In [36]:
import pandas as pd
import numpy as np

dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print(df[0:3])
print(df['20130102':'20130104'])

                   A         B         C         D
2013-01-01  2.003139 -0.790490 -1.217610 -0.529998
2013-01-02  0.163046 -1.143857 -1.031542  2.132619
2013-01-03  0.791178  1.211458  0.935217  0.309789
2013-01-04  0.423494  2.022629 -1.337434 -0.515317
2013-01-05  0.094350 -1.563637 -0.470881  1.104426
2013-01-06 -0.336941  1.154172 -0.584901  0.655437
                   A         B         C         D
2013-01-01  2.003139 -0.790490 -1.217610 -0.529998
2013-01-02  0.163046 -1.143857 -1.031542  2.132619
2013-01-03  0.791178  1.211458  0.935217  0.309789
                   A         B         C         D
2013-01-02  0.163046 -1.143857 -1.031542  2.132619
2013-01-03  0.791178  1.211458  0.935217  0.309789
2013-01-04  0.423494  2.022629 -1.337434 -0.515317


In [38]:
import pandas as pd
import numpy as np

dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print(df.loc[dates[0]])

                   A         B         C         D
2013-01-01 -0.849846  1.053002  1.266273  1.430079
2013-01-02 -0.146510  0.845620 -2.399594 -1.719288
2013-01-03  0.348975  1.072931 -0.648261 -0.245363
2013-01-04  1.488202 -1.638637 -2.756781  0.155028
2013-01-05 -1.115967  1.237533 -0.837260  1.377862
2013-01-06 -0.056326 -2.474189  1.565977 -0.797959
A   -0.849846
B    1.053002
C    1.266273
D    1.430079
Name: 2013-01-01 00:00:00, dtype: float64


In [39]:
import pandas as pd
import numpy as np

dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df.loc[:, ['A', 'B']])

                   A         B
2013-01-01 -1.370018 -0.574305
2013-01-02  0.706941  0.935660
2013-01-03 -0.967871  0.108171
2013-01-04  0.294053 -0.146322
2013-01-05 -1.772306 -0.998169
2013-01-06 -0.556847  0.781103


In [42]:
import pandas as pd
import numpy as np

dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print(df.iloc[3:5, 0:2])

                   A         B         C         D
2013-01-01  0.054293  1.078311  1.443427  0.303122
2013-01-02 -0.188155  0.328037  0.647265 -0.330420
2013-01-03 -1.306959  0.872586  0.896142  1.301487
2013-01-04  0.362863 -0.729515 -0.244917 -1.478310
2013-01-05 -0.572564 -0.274823 -1.715368 -0.007437
2013-01-06  0.071147 -1.299491  1.653523  1.125381
                   A         B
2013-01-04  0.362863 -0.729515
2013-01-05 -0.572564 -0.274823


In [45]:
for i in range(1,5):
    print(i)

1
2
3
4


In [50]:
a=df.iloc[1:2,1:2]
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [51]:
import pandas as pd

# 创建包含类型 A、B、C 的列
df = pd.DataFrame({'column_name': ['A', 'B', 'C', 'A', 'B', 'C']})

# 使用 replace 方法进行映射
df['column_name'] = df['column_name'].replace({'A': 1, 'B': 2, 'C': 3})

# 打印转换后的 DataFrame
print(df)

   column_name
0            1
1            2
2            3
3            1
4            2
5            3


In [68]:
import pandas as pd
import numpy as np

dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print(df[df.loc[:,'A'] > 0])
print(df[df.A>0])
print(df[df['A']>0])

                   A         B         C         D
2013-01-01  1.140743  1.581185  1.461802 -0.011686
2013-01-02  1.240905 -0.038972  0.126328  0.099751
2013-01-03 -0.046743  1.033929 -0.719915  0.174735
2013-01-04  0.585966  2.913194 -0.123065  0.157037
2013-01-05 -0.364586  1.491276 -0.245363 -0.702295
2013-01-06  1.836537  0.621763  0.337140 -0.355537
                   A         B         C         D
2013-01-01  1.140743  1.581185  1.461802 -0.011686
2013-01-02  1.240905 -0.038972  0.126328  0.099751
2013-01-04  0.585966  2.913194 -0.123065  0.157037
2013-01-06  1.836537  0.621763  0.337140 -0.355537
                   A         B         C         D
2013-01-01  1.140743  1.581185  1.461802 -0.011686
2013-01-02  1.240905 -0.038972  0.126328  0.099751
2013-01-04  0.585966  2.913194 -0.123065  0.157037
2013-01-06  1.836537  0.621763  0.337140 -0.355537
                   A         B         C         D
2013-01-01  1.140743  1.581185  1.461802 -0.011686
2013-01-02  1.240905 -0.038972 

In [76]:
import pandas as pd
import numpy as np
np.random.seed(123)
dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print( df > 0)

                   A         B         C         D
2013-01-01 -1.085631  0.997345  0.282978 -1.506295
2013-01-02 -0.578600  1.651437 -2.426679 -0.428913
2013-01-03  1.265936 -0.866740 -0.678886 -0.094709
2013-01-04  1.491390 -0.638902 -0.443982 -0.434351
2013-01-05  2.205930  2.186786  1.004054  0.386186
2013-01-06  0.737369  1.490732 -0.935834  1.175829
                A      B      C      D
2013-01-01  False   True   True  False
2013-01-02  False   True  False  False
2013-01-03   True  False  False  False
2013-01-04   True  False  False  False
2013-01-05   True   True   True   True
2013-01-06   True   True  False   True


In [77]:
import pandas as pd
import numpy as np

dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))

df2 = df.copy()
df2['E'] = ['one', 'one', 'two', 'three', 'four', 'three']

print(df2)

print(df2[df2['E'].isin(['two', 'four'])])

                   A         B         C         D      E
2013-01-01 -1.253881 -0.637752  0.907105 -1.428681    one
2013-01-02 -0.140069 -0.861755 -0.255619 -2.798589    one
2013-01-03 -1.771533 -0.699877  0.927462 -0.173636    two
2013-01-04  0.002846  0.688223 -0.879536  0.283627  three
2013-01-05 -0.805367 -1.727669 -0.390900  0.573806   four
2013-01-06  0.338589 -0.011830  2.392365  0.412912  three
                   A         B         C         D     E
2013-01-03 -1.771533 -0.699877  0.927462 -0.173636   two
2013-01-05 -0.805367 -1.727669 -0.390900  0.573806  four


In [78]:
import pandas as pd
import numpy as np

s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range('20130102', periods=6))
print(s1)

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64
